vich_uploader:
    db_driver: orm
    mappings:
        event_images:
            uri_prefix: /uploads/images/events
            upload_destination: '%kernel.project_dir%/public/uploads/images/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer